# Generated by Django 2.2.9 on 2021-03-17 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, verbose_name='nome')),
                ('categoria', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categoria.Categoria')),
            ],
            options={
                'db_table': 'perfil',
            },
        ),
    ]
