# Generated by Django 2.2.9 on 2021-03-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, verbose_name='nome')),
                ('tipo', models.CharField(max_length=250, verbose_name='tipo')),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
    ]
