# Generated by Django 2.2.9 on 2021-03-31 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensagem', '0002_auto_20210317_1345'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mensagem',
            table='Mensagen',
        ),
    ]
